### PR TITLE
added Taurean Bryant

### PR DESCRIPTION
**Pull request by taurean**
Added my new portfolio

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
The purpose of Awesome Portfolios is not to highlight the work of an individual, or to be used as a form of self-promotion. It is to highlight the *presentation* of that work.

This portfolio is in no way creative. It's about as basic as they come in presentation.

**Comment by taurean** [comment]
Jesus. I understand where you’re coming from but I think you know you could have handled that better. I would suggest adding actual contribution guidelines to your contribution guidelines section.

**Comment by TheJaredWilcurt** [comment]
@taurean this isn't my project, I just watch it to see cool shit get added, not boring self promotion spam. I don't care if you are here to just advertise yourself but if it isn't in an impressive, original, or unique way, what's the point

**Comment by taurean** [comment]
@TheJaredWilcurt So ignoring the fact that there are already portfolios incredibly similar to mine in this directory, are you going to say its necessary to hurl insults like this?

**Comment by keiranlovett** [comment]
@taurean Awesome Portfolios is repository for websites that present content in an interest, unique, or creative way - its not for the content itself. 

While your website is fine, it can easily fit in with a generic website template, this is why @TheJaredWilcurt has closed the issue.

**Comment by taurean** [comment]
As I’ve said, I don’t have any issue being rejected. I’m not disputing the rejection, I’m disputing his tone which wasn’t necessary. We can leave it at that.

**Pull request closed without merging**
