### PR TITLE
Added a new portfolio website - specifically an Agency portfolio site…

### PR DESCRIPTION
**Pull request by imisterk**
… + made comments

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
The description for this repo is

```
A curated list of Awesome Creative Portfolio Websites, created by creative Developers/Designers
```

Which is why there is a list of **Developers/Designers**, which are all individuals. The site you linked to just looks like a business website. It isn't a personal portfolio. I don't think it really fits on this list, categorically.

**Comment by imisterk** [comment]
You are completely right, hence the comment I have made in the readme. I do believe there are many agencies out there that have very creative as well as very technically advanced websites. 

**Why not add an additional category** to showcase that as well? The only difference between the two categories would literately be the amount of people that work on the website (one opposed to a collaboration).

At the end of the day, the compiled list is for us the consumers, aspiring devs/designers who can appreciate both. I believe I can speak for the majority here, we would like to see both :) + more content for you and your website so in reality, it's a win win.

**PS:**
I am not trying to plug Humaan, but would like to push that side of this list, the agency list.

**Comment by TheJaredWilcurt** [comment]
The difference is not solely the number of contributors to a project, but also the intent and motivation. With an agency there is a financial motivation and they are paying the contributors to produce a marketable result. 

I am not the maintainer or creator of this repo. It seems pretty obvious to me it's current purpose, to display the portfolios of individual devs/designers, and to leave list of other content to other sites. However that may not be the future of the repo, @iRaul may want to expand out to cover more than what this repo is doing currently.

But with only one item under agency it may feel more like an advertisement than a list.

**Comment by imisterk** [comment]
I agree, with only one item in that category it would definitely seem like a advertisement and I think that statement alone puts a nail in the coffin for this addition. 

However I still believe that any portfolio should be mentioned, no matter if its contribution of multiple devs/designers or just individuals. One thing to note, just because its an agency does not mean more than 2 people had an input on the website. Just as it is likely that some* singular portfolios might had more than 1 person working on it as well. 

Additionally, individual portfolios are also financially motivated to create their portfolio, in most cases at least.

**Comment by TheJaredWilcurt** [comment]
I think that update is a good change overall. Though, outside of humaan, I don't think the other agencies porfolios really stand out from the norm when it comes to execution.

Remember that the point of this repo is not to show portfolio's with good content, but portfolios that display their content in unique and creative ways. For example, northkingdom.com/work is about as boring of a presentation as it comes.

Although, interestingly, `interface-design.co.uk` has a design almost identical to `jennyjohannesson.com` which is currently on the list for portfolios.

What I want to see is more stuff like `bellbros.com`, unique, well executed ideas.

**Pull request merged**
