### PR TITLE
Add some portfolios.

### PR DESCRIPTION
**Pull request by lhbzr**
- [Giulian Drimba](http://doublepi.me/)
- [Silvio Paganini](http://s2paganini.com/)
- [Bruno Imbrizi](http://brunoimbrizi.com/)
- [Du Haihang](http://www.duhaihang.com/portfolio/2016/)
- [Edan Kwan](http://edankwan.com/)
- [Clément Pavageau](http://kokopako.fr/)
- [Danilo Figueiredo](http://www.grifo.tv/)
- [Steven Mengin](https://stevenmengin.com/)
- [Luis Henrique Bizarro](https://lhbzr.com/)

### CODE REVIEW

**Comment by iRaul** [comment]
@lhbzr Awesome websites man! Thank you! You can add yours too 👍

**Comment by lhbzr** [comment]
@iRaul I will, thank you very much! Let me add some more portfolios then you can merge the changes. 😄

**Comment by iRaul** [comment]
@lhbzr Sounds good :)

**Comment by lhbzr** [comment]
That's all for the moment, but I'll keep contributing. That's a really cool repo Raul, congratulations! 🌠

**Comment by iRaul** [comment]
@lhbzr Thanks! Awesome websites. Two of them are already in the list, but no problem. I'll delete them 👍

**Comment by lhbzr** [comment]
@iRaul I'm sorry! Next time I'll check the list more wisely! 😆

**Pull request merged**
