### PR TITLE
Adding Edward Huang's Portfolio

### PR DESCRIPTION
**Pull request by edwardGunawan**
Hope you find the design and content useful for future inspiration :)

### CODE REVIEW

**Comment by TheJaredWilcurt** [comment]
The design and layout are very nice looking.

It doesn't really blow my socks off though. It's a good combination of libraries like jQuery, sweetscroll/scrollreveal, and  Jonathan Nicol's *Particle Ground*. But in the parts where you aren't relying on other's work, it's pretty boring/unimpressive.

And I'm not sure what libraries you are using for styling, but according to Chrome's audit, 97% of your classes are not in use.

**Comment by edwardGunawan** [comment]
Hi Jared, 

Thank you so much for the comment and feedback. I used Bulma css library for layout and styling to create easy to read and minimalist look.  Do you have any recommendation on what I should be adding to my portfolios (improving), such as more visual appearance, or more basic implementation without any other libraries to be able to be consider as awesome-portfolio? This is my first pull request. Therefore, I would like to know if I do update my portfolio and add something, will I be able to submit another pull request? 

Thank you so much again for the criticism and feedback!

**Comment by TheJaredWilcurt** [comment]
@edwardGunawan 

I don't think your focus should be on "Make something to get on this list". You likely already have goals for your portfolio, like to impress a potential employer, or just as a place to keep track of the work you've done. Whatever your primary intention is for the portfolio, that should be your focus.

I don't believe there is a written set of criteria for what can and cannot be added to the list here. Certain things I would look for are creative, unique designs, that showcase both originality, and high technical skill. These should be impressive enough that the creator of it, doesn't have to be the person submitting it.

When I made my portfolio, my goal was primarily to have an easily updatable location to store a list of my completed projects. My goal was not to be showcased for my technical skill, or original designs, just to look good enough, and list everything.

Your portfolio is fine, I don't think you need to change anything about it. Focus on what your real goals are.

**Comment by edwardGunawan** [comment]
@TheJaredWilcurt 


Thank you so much for the insights and advice!

**Pull request closed without merging**
